export const SITE_NAME = "SELECT * FROM life;"
export const DISQUS_SHORT_NAME = "yuku-blog"
export const PRIMARY_COLOR = "#00BCD4"
export const SECONDARY_COLOR = "#6c757d"
export const SUCCESS_COLOR = "#28a745"
export const INFO_COLOR = "#17a2b8"
export const WARNING_COLOR = "#ffc107"
export const DANGER_COLOR = "#dc3545"
