// Auto generated by script/extract-metadata
import moment from "moment"
export default [
  {
    href: "blog/2018/12/hello-world-again",
    publishedAt: moment("2018-12-29T23:59:00+09:00"),
    title: "Hello World Again",
  },
  {
    href: "blog/2018/12/hello-world",
    publishedAt: moment("2018-12-29T10:25:00+09:00"),
    title: "Hello World",
  },
]
