name: Topic Branch Workflow
on:
  push:
    branches-ignore: [workspace]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: yarn install
    - run: yarn build
    - run: '[ -e public/static/rss-feed.xml ]'
    - run: yarn test
